//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROC.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class News
    {
        public int Id { get; set; }
        [DataType(DataType.DateTime)]
        [Editable(false)]
        [ScaffoldColumn(false)]
        public System.DateTime ModifiedTime { get; set; }
        public string Title { get; set; }
        public string Source { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime ContentTime { get; set; }
        public string MainContent { get; set; }

        public int CategoryID { get; set; }

        public IEnumerable<NewsCategory> CategorysList { get;set; }

        
    }
}
