//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureStory
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Source { get; set; }
        public string DetailContent { get; set; }
        public int CategoryID { get; set; }
    }
}
