//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ROCDBContainer : DbContext
    {
        public ROCDBContainer()
            : base("name=ROCDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<News> NewsSet { get; set; }
        public DbSet<NewsCategory> NewsCategorySet { get; set; }
        public DbSet<ProjectCategory> ProjectCategorySet { get; set; }
        public DbSet<Projects> ProjectsSet { get; set; }
        public DbSet<ProjectDetail> ProjectDetailSet { get; set; }
        public DbSet<PictureStory> PictureStorySet { get; set; }
        public DbSet<PictureStoryCategory> PictureStoryCategorySet { get; set; }
    }
}
